#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'test-topic','console_scripts','preform_test'
__requires__ = 'test-topic'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('test-topic', 'console_scripts', 'preform_test')()
    )
